### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by Uzair-Manzoor** [Uzair-Manzoor/RubyCapstone#34]
This issue has been created to provide task assignments and team information for [Ruby Group Capstone](https://github.com/Uzair-Manzoor/RubyCapstone/projects/1) project:

We are team of 3 participants working on this project:

@ismayito 
@Uzair-Manzoor 
@Ayokunnumi1

**Comment by Omar-Muhamad** [comment]
# Changes Required ♻️
### Hi @Uzair-Manzoor, @ismayito, and @Ayokunnumi1,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20the%20number%20of%20points), Each task supposed to have the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. Please add this to the task title.

- [ ] There are 5 tasks created without a description and there are others that need a proper description with steps on what you will do inside these tasks. Please fix that.

| Tasks missing desceipion  | Tasks missing desceipion |
| ------------- | ------------- |
| ![image](https://github.com/Uzair-Manzoor/RubyCapstone/assets/68796232/1fe4da40-4041-46cc-9f65-188bbbfd5202)  | ![image](https://github.com/Uzair-Manzoor/RubyCapstone/assets/68796232/7b81a15f-949f-43da-966f-736c7c4d6b69) |

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Uzair-Manzoor** [comment]
Hello @Omar-Muhamad, thank you for the insightful feedback. Changes have been made accordingly.

**Comment by ridwanediallo** [comment]
# STATUS: APPROVED 🟢
## Hi team, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done, team, for implementing the requested changes. You are now good to go. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
